


#                  __      __              
#     ____  ____  / /_  __/ /_  ____ ______
#    / __ \/ __ \/ / / / / __ \/ __ `/ ___/
#   / /_/ / /_/ / / /_/ / /_/ / /_/ / /    
#  / .___/\____/_/\__, /_.___/\__,_/_/     
# /_/            /____/                    


[colors]
foreground = #ffffff
foreground-alt = #000000
background = #000000
#background-alt = #1e1e2e
background-alt = #ffc5d3


[bar/main]
bottom = false
width = 100%
height = 12pt
background = ${colors.background}
foreground = ${colors.foreground}
border-size = 0pt
line-size = 0pt

font-0 = UbuntuMono Nerd Font:size=10;1

separator = " "
modules-left = workspaces tray
modules-right = memory pulseaudio date


[module/workspaces]
type = internal/i3
format = <label-state>

wm-restack = i3
index-sort = true
wrapping-scroll = false
strip-wsnumbers = true
pin-workspaces = true

label-focused = %name%
label-focused-background = ${colors.background-alt}
label-focused-foreground = ${colors.foreground-alt}
label-focused-padding = 5pt

label-unfocused = %name%
label-unfocused-background = ${colors.background}
label-unfocused-foreground = ${colors.foreground}
label-unfocused-padding = 5pt


[module/tray]
type = internal/tray

tray-background = ${colors.background}
tray-foreground = ${colors.foreground}


[module/memory]
type = internal/memory

format = ram <label>
format-background = ${colors.background}
format-foreground = ${colors.foreground}
format-padding = 1pt


[module/pulseaudio]
type = internal/pulseaudio

format-volume = vol <label-volume>%
format-volume-foreground = ${colors.foreground}
format-volume-background = ${colors.background}
format-volume-padding = 1pt
label-volume = %percentage%

format-muted = vol <label-muted>x
format-muted-foreground = ${colors.foreground}
format-muted-background = ${colors.background}
format-muted-padding = 1pt
label-muted = %percentage%


[module/date]
type = internal/date

format = <label>
format-background = ${colors.background}
format-foreground = ${colors.foreground}
format-padding = 2pt

interval = 1
date = %d %b %Y
time = %H:%M
label = %date% %time%
