


#                  __      __              
#     ____  ____  / /_  __/ /_  ____ ______
#    / __ \/ __ \/ / / / / __ \/ __ `/ ___/
#   / /_/ / /_/ / / /_/ / /_/ / /_/ / /    
#  / .___/\____/_/\__, /_.___/\__,_/_/     
# /_/            /____/                    


[colors]
foreground = #ffffff
background = #00000000
foreground-alt = #000000
background-alt = #ffc5d3

warning = #ffff99
error = ff746c


[settings]
pseudo-transparency = true
format-background = ${colors.background}
format-foreground = ${colors.foreground}
format-padding = 1pt


[bar/main]
bottom = false
width = 100%
height = 12pt
border-size = 0pt
line-size = 0pt
background = #00000000

font-0 = UbuntuMono Nerd Font:size=10;1

modules-left = workspaces
modules-right = cpu-discrete memory-discrete volume-discrete date


[bar/detail]
bottom = false
width = 100%
height = 12pt
border-size = 0pt
line-size = 0pt
background = #00000000

font-0 = UbuntuMono Nerd Font:size=10;1

separator = " "
modules-left = workspaces tray
modules-center = date-seconds
modules-right = cpu memory volume


[bar/off]
height = 0pt
border-size = 0pt
line-size = 0pt


[module/cpu]
type = internal/cpu
interval = 0.1
warn-percentage = 25

format = <label>
label = cpu %percentage%%
label-warn = cpu %percentage%%
label-warn-foreground = ${colors.warning}


[module/cpu-discrete]
inherit = module/cpu

label = ""
label-warn = "cpu "


[module/date]
type = internal/date
interval = 1

format = <label>

date = %d %b %Y
time = %R
label = %date% %time%


[module/date-seconds]
inherit = module/date

interval = 0.5
time = %T


[module/memory]
type = internal/memory

format = <ramp-used> <label>

ramp-used-0 = ram
ramp-used-0-weight = 2

ramp-used-1 = ram
ramp-used-1-foreground = ${colors.warning}
ramp-used-1-weight = 1

ramp-used-2 = ram
ramp-used-2-foreground = ${colors.error}
ramp-used-2-weight = 1


[module/memory-discrete]
inherit = module/memory

format = <ramp-used>

ramp-used-0 = ""
ramp-used-1 = "ram "
ramp-used-2 = "ram "


[module/volume]
type = internal/pulseaudio

format-muted = vol <label-muted>x
label-muted = %percentage%

format-volume = <ramp-volume> <label-volume>%
label-volume = %percentage%

ramp-volume-0 = vol
ramp-volume-0-weight = 2

ramp-volume-1 = vol
ramp-volume-1-foreground = ${colors.warning}
ramp-volume-1-weight = 1

ramp-volume-2 = vol
ramp-volume-2-foreground = ${colors.error}
ramp-volume-2-weight = 1


[module/volume-discrete]
inherit = module/volume

format-muted = "vol x "
format-volume = <ramp-volume>

ramp-volume-0 = ""
ramp-volume-1 = "vol "
ramp-volume-2 = "vol "


[module/tray]
type = internal/tray


[module/workspaces]
type = internal/i3
format = <label-state>

wm-restack = i3
index-sort = true
wrapping-scroll = false
strip-wsnumbers = true
pin-workspaces = true

label-focused = %name%
label-focused-background = ${colors.background-alt}
label-focused-foreground = ${colors.foreground-alt}
label-focused-padding = 5pt

label-unfocused = %name%
label-unfocused-background = ${colors.background}
label-unfocused-padding = 5pt
