


#                  __      __              
#     ____  ____  / /_  __/ /_  ____ ______
#    / __ \/ __ \/ / / / / __ \/ __ `/ ___/
#   / /_/ / /_/ / / /_/ / /_/ / /_/ / /    
#  / .___/\____/_/\__, /_.___/\__,_/_/     
# /_/            /____/                    


[colors]
foreground = #ffffff
background = #000000
foreground-alt = #000000
background-alt = #ffc5d3

warning = #ffff99
error = ff746c


[settings]
pseudo-transparency = true
format-background = ${colors.background}
format-foreground = ${colors.foreground}

format-padding = 1pt


[bar/main]
bottom = false
width = 100%
height = 12pt
border-size = 0pt
line-size = 0pt
background = #00000000

font-0 = UbuntuMono Nerd Font:size=10;1

modules-left = workspaces
modules-right = memory-discrete volume-discrete date


[module/cpu]
type = internal/cpu

format = cpu <label>


[module/date]
type = internal/date

format = <label>

interval = 1
date = %d %b %Y
time = %H:%M
label = %date% %time%


[module/memory]
type = internal/memory

format = <ramp-used>

ramp-used-0-weight = 2

ramp-used-1-foreground = ${colors.warning}
ramp-used-1-weight = 1

ramp-used-2-foreground = ${colors.error}
ramp-used-2-weight = 1


[module/memory-discrete]
inherit = module/memory

format = <ramp-used>

ramp-used-0 = ""
ramp-used-1 = "ram "
ramp-used-2 = "ram "


[module/volume]
type = internal/pulseaudio

format-volume = vol <label-volume>%
label-volume = %percentage%

format-muted = vol <label-muted>x
label-muted = %percentage%

ramp-volume-0-weight = 2

ramp-volume-1-foreground = ${colors.warning}
ramp-volume-1-weight = 1

ramp-volume-2-foreground = ${colors.error}
ramp-volume-2-weight = 1


[module/volume-discrete]
inherit = module/volume

format-volume = <ramp-volume>
format-muted = "vol x "

ramp-volume-0 = ""
ramp-volume-1 = "vol "
ramp-volume-2 = "vol "


[module/tray]
type = internal/tray


[module/workspaces]
type = internal/i3
format = <label-state>

wm-restack = i3
index-sort = true
wrapping-scroll = false
strip-wsnumbers = true
pin-workspaces = true

label-focused = %name%
label-focused-background = ${colors.background-alt}
label-focused-foreground = ${colors.foreground-alt}
label-focused-padding = 5pt

label-unfocused = %name%
label-unfocused-padding = 5pt
